### PR TITLE
feat: Update the deps and the Golang version to 1.20

### PR DESCRIPTION
**Pull request by ZPascal**
**Features:**
- Update the Golang libs
- Update the Golang version
- Fix the GH Actions

**Breaking changes:**
- Change of the release name of the GoReleaser artifacts 
Bildschirmfoto von 2023-07-24 21 40 42

### CODE REVIEW

**Comment by ZPascal** [comment]
@fritterhoff Do you have an opinion on this?

**Comment by ZPascal** [comment]
@fritterhoff Should I add some additional information?

**Comment by fritterhoff** [comment]
Hi @ZPascal,
excuse my late reply. That looks good to me.

**Comment by ZPascal** [comment]
Thank you, @fritterhoff

**Pull request merged**
